### ISSUE TITLE
Question: Overwriting of M in the definition of ardca function in ar.jl

### ISSUE THREAD

**Issue by tferracina** [pagnani/ArDCA.jl#37]
Hi, I noticed that in the definition of ardca() we have:
```
Z_copy = copy(Z)
N, M = size(Z_copy)
M = length(W)
q = Int(maximum(Z_copy))
```

I am wondering why the M definition is overwritten as length(W). Also, just to double check my understanding the Z_copy is created to be passed into the ArVar function without editing the original Z right?

Thanks in advance, 
Tommaso

**Comment by pagnani** [comment]
Hi @tferracina 

This is a dirty patch to avoid permuting the user's input. I did not want to modify what the user fed the algorithm. Duplicating the MSA typically makes little difference, because the parameters generally dominate the memory. However, if you have a gigantic MSA (sometimes it happens), it could matter. Are you incurring some OOM problems? If yes I might come up with a way to do it properly. What I do not like is that if you ctrl-c before the end of the run, I could end up with a corruption of the input which I find unfair. The logic of the permutation of sites is a bit brittle, I must admit.

**Comment by tferracina** [comment]
Hello and thanks for the reply. 

The question actually came as I am currently working on translating the project into Python. Unfortunately I do not have a lot of experience with Julia so I'm afraid I won't be able to offer much support there, although the current implementation of duplicating the MSA makes sense to me.

For the overwriting of the definition of M maybe adding a check could work:
``` 
N, M = size(Z_copy)
M == length(W) || throw("columns in Z must match length of W")
```

Thanks!

**Comment by pagnani** [comment]
Yes you are right ... I should insert the check you propose .. mind opening a PR so that I don't forget to add it ?

A
